#!/usr/bin/env bash
# Shared, fixed WHU protocol for the four-row Prompt/P2 matrix.
# This file is sourced by the row wrappers; do not execute it directly.

export NECK_TYPE="pafpn"
export PROMPT_ROUTE="coarse"
export SAM_IMAGE_EMBED_STRIDE=16
export FINAL_MASK_COORDINATE_MODE="roi_local"
export SHAPE_DENSE_TRANSFORM="raw_logits"

# The matrix verifies an end-to-end prompt path.  In particular, its dense
# rows keep the graph from final-mask loss to coarse/P2-BRR open.
export SHAPE_DENSE_DETACH="${SHAPE_DENSE_DETACH:-0}"

# Same accelerated WHU protocol as the recent C5-v2 full-data run.
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
export NPROC_PER_NODE="${NPROC_PER_NODE:-4}"
export AMP="${AMP:-1}"
export BATCH_SIZE="${BATCH_SIZE:-1}"
export GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-2}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export MAX_EPOCHS="${MAX_EPOCHS:-150}"
export TRAIN_SUBSET_RATIO="${TRAIN_SUBSET_RATIO:-1.0}"
export VAL_SUBSET_RATIO="${VAL_SUBSET_RATIO:-1.0}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-2}"
export FINAL_MASK_TARGET_SIZE="${FINAL_MASK_TARGET_SIZE:-256}"
export CUDNN_BENCHMARK="${CUDNN_BENCHMARK:-1}"
export TEST_MAX_PER_IMG="${TEST_MAX_PER_IMG:-100}"
export EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-20}"
export EARLY_STOPPING_START_EPOCH="${EARLY_STOPPING_START_EPOCH:-90}"
export EARLY_STOPPING_MIN_DELTA="${EARLY_STOPPING_MIN_DELTA:-5e-4}"
export EARLY_STOPPING_SMOOTH_WINDOW="${EARLY_STOPPING_SMOOTH_WINDOW:-5}"
export EMA_ENABLED="${EMA_ENABLED:-1}"
export EMA_EVAL="${EMA_EVAL:-0}"
export EMA_SAVE_BEST="${EMA_SAVE_BEST:-0}"
export SAVE_BBOX_BEST_METRIC="${SAVE_BBOX_BEST_METRIC:-}"
export TRAIN_VFLIP_PROB="${TRAIN_VFLIP_PROB:-0.5}"
export TRAIN_MULTI_SCALE_RESIZE_PROB="${TRAIN_MULTI_SCALE_RESIZE_PROB:-0.5}"
export TRAIN_MULTI_SCALE_MODE="${TRAIN_MULTI_SCALE_MODE:-value}"
export TRAIN_MULTI_SCALE_IMG_SCALE="${TRAIN_MULTI_SCALE_IMG_SCALE:-896:896,960:960,1024:1024,1088:1088,1152:1152}"
export SUBSET_SEED="${SUBSET_SEED:-44}"
export LEARNING_RATE="${LEARNING_RATE:-5e-4}"
export WEIGHT_DECAY="${WEIGHT_DECAY:-0.05}"
export WARMUP_ITERS="${WARMUP_ITERS:-100}"
export PROMPT_ENCODER_LR_MULT="${PROMPT_ENCODER_LR_MULT:-0.0}"
export SHAPE_PRIOR_LOSS_WEIGHT="${SHAPE_PRIOR_LOSS_WEIGHT:-0.10}"
export P2_BOUNDARY_REFINER_PROJECTED_CHANNELS="${P2_BOUNDARY_REFINER_PROJECTED_CHANNELS:-64}"
export P2_BOUNDARY_REFINER_MID_CHANNELS="${P2_BOUNDARY_REFINER_MID_CHANNELS:-64}"
export P2_BOUNDARY_REFINER_LOSS_WEIGHT="${P2_BOUNDARY_REFINER_LOSS_WEIGHT:-0.05}"
export POINT_WARMUP_ENABLED="${POINT_WARMUP_ENABLED:-0}"
